//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Morozov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public double AreaSize { get; set; }
        public System.DateTime Date { get; set; }
        public int Grops { get; set; }
        public int Status { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual status status1 { get; set; }
    }
}
